# Generated by Django 2.0.7 on 2018-07-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20180728_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
    ]
